### ISSUE TITLE
Missing "./utils" specifier in "typesafe-i18n" package

### ISSUE THREAD

**Issue by gevera** [ciscoheat/typesafe-i18n-with-sveltekit#1]
Having issues running your demo. After cloning the repo getting the following error:

```bash
Error: Missing "./utils" specifier in "typesafe-i18n" package
```

**Comment by ciscoheat** [comment]
I've just reported this to the package maintainer. Hopefully it will be a quick fix: https://github.com/ivanhofer/typesafe-i18n/issues/590

**Comment by ciscoheat** [comment]
A workaround for now is to use this version in `package.json`:

```
"typesafe-i18n": "~5.22.0",
```

**Comment by gevera** [comment]
Thanks for quick reply. I will test it out

**Comment by ciscoheat** [comment]
It should be working again now with 5.23.2!

**Comment by gevera** [comment]
Yeah, just have updated it to 5.23.2 and it works. Thank you
